import { z } from "zod";
export declare const TaskStatusEnum: z.ZodEnum<["To Do", "In Progress", "In Review", "Done"]>;
export declare const TaskPriorityEnum: z.ZodEnum<["Low", "Medium", "High"]>;
export declare const TaskEstimateEnum: z.ZodEnum<["S", "M", "L"]>;
export declare const TaskSchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    status: z.ZodEnum<["To Do", "In Progress", "In Review", "Done"]>;
    priority: z.ZodEnum<["Low", "Medium", "High"]>;
    estimate: z.ZodEnum<["S", "M", "L"]>;
    definitionOfDone: z.ZodNullable<z.ZodString>;
    notes: z.ZodNullable<z.ZodString>;
    projectId: z.ZodNullable<z.ZodString>;
    agentId: z.ZodNullable<z.ZodString>;
    skillId: z.ZodNullable<z.ZodString>;
    createdAt: z.ZodString;
    updatedAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    status: "To Do" | "In Progress" | "In Review" | "Done";
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
    projectId: string | null;
    agentId: string | null;
    priority: "Low" | "Medium" | "High";
    estimate: "S" | "M" | "L";
    definitionOfDone: string | null;
    notes: string | null;
    skillId: string | null;
}, {
    status: "To Do" | "In Progress" | "In Review" | "Done";
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
    projectId: string | null;
    agentId: string | null;
    priority: "Low" | "Medium" | "High";
    estimate: "S" | "M" | "L";
    definitionOfDone: string | null;
    notes: string | null;
    skillId: string | null;
}>;
export declare const CreateTaskSchema: z.ZodObject<{
    name: z.ZodString;
    status: z.ZodDefault<z.ZodOptional<z.ZodEnum<["To Do", "In Progress", "In Review", "Done"]>>>;
    priority: z.ZodOptional<z.ZodEnum<["Low", "Medium", "High"]>>;
    estimate: z.ZodOptional<z.ZodEnum<["S", "M", "L"]>>;
    definitionOfDone: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    notes: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    projectId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    agentId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    skillId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    status: "To Do" | "In Progress" | "In Review" | "Done";
    name: string;
    projectId?: string | null | undefined;
    agentId?: string | null | undefined;
    priority?: "Low" | "Medium" | "High" | undefined;
    estimate?: "S" | "M" | "L" | undefined;
    definitionOfDone?: string | null | undefined;
    notes?: string | null | undefined;
    skillId?: string | null | undefined;
}, {
    name: string;
    status?: "To Do" | "In Progress" | "In Review" | "Done" | undefined;
    projectId?: string | null | undefined;
    agentId?: string | null | undefined;
    priority?: "Low" | "Medium" | "High" | undefined;
    estimate?: "S" | "M" | "L" | undefined;
    definitionOfDone?: string | null | undefined;
    notes?: string | null | undefined;
    skillId?: string | null | undefined;
}>;
export declare const UpdateTaskSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    status: z.ZodOptional<z.ZodDefault<z.ZodOptional<z.ZodEnum<["To Do", "In Progress", "In Review", "Done"]>>>>;
    priority: z.ZodOptional<z.ZodOptional<z.ZodEnum<["Low", "Medium", "High"]>>>;
    estimate: z.ZodOptional<z.ZodOptional<z.ZodEnum<["S", "M", "L"]>>>;
    definitionOfDone: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    notes: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    projectId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    agentId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    skillId: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
}, "strip", z.ZodTypeAny, {
    status?: "To Do" | "In Progress" | "In Review" | "Done" | undefined;
    name?: string | undefined;
    projectId?: string | null | undefined;
    agentId?: string | null | undefined;
    priority?: "Low" | "Medium" | "High" | undefined;
    estimate?: "S" | "M" | "L" | undefined;
    definitionOfDone?: string | null | undefined;
    notes?: string | null | undefined;
    skillId?: string | null | undefined;
}, {
    status?: "To Do" | "In Progress" | "In Review" | "Done" | undefined;
    name?: string | undefined;
    projectId?: string | null | undefined;
    agentId?: string | null | undefined;
    priority?: "Low" | "Medium" | "High" | undefined;
    estimate?: "S" | "M" | "L" | undefined;
    definitionOfDone?: string | null | undefined;
    notes?: string | null | undefined;
    skillId?: string | null | undefined;
}>;
export type TaskStatus = z.infer<typeof TaskStatusEnum>;
export type TaskPriority = z.infer<typeof TaskPriorityEnum>;
export type TaskEstimate = z.infer<typeof TaskEstimateEnum>;
export type Task = z.infer<typeof TaskSchema>;
export type CreateTask = z.infer<typeof CreateTaskSchema>;
export type UpdateTask = z.infer<typeof UpdateTaskSchema>;
//# sourceMappingURL=tasks.schema.d.ts.map