// Services
import { ActivityLogService } from './activity-log/activity-log.service.js';
import { AgentProvidersService } from './agent-providers/agent-providers.service.js';
import { AgentsService } from './agents/agents.service.js';
import { AuthService } from './auth/auth.service.js';
import { BriefGeneratorService } from './brief-generator/brief-generator.service.js';
import { DesignContextGeneratorService } from './design-context-generator/design-context-generator.service.js';
import { ChatService } from './chat/chat.service.js';
import { FilesystemService } from './filesystem/filesystem.service.js';
import { HeartbeatService } from './heartbeat/heartbeat.service.js';
import { IntegrationsService } from './integrations/integrations.service.js';
import { ObsidianService } from './integrations/obsidian.service.js';
import { SupermemoryService } from './integrations/supermemory.service.js';
import { McpServersService } from './mcp-servers/mcp-servers.service.js';
import { MemoryService } from './memory/memory.service.js';
import { OrchestratorService } from './orchestrator/index.js';
import { DocsGeneratorService } from './project-docs/docs-generator.service.js';
import { ProjectDocsService } from './project-docs/project-docs.service.js';
import { MarketplaceService } from './marketplace/marketplace.service.js';
import { PackageExporterService } from './package-io/package-exporter.service.js';
import { PackageImporterService } from './package-io/package-importer.service.js';
import { WorkflowRunnerService } from './workflow-runner/workflow-runner.service.js';
import { PhasesService } from './phases/phases.service.js';
import { PreferencesService } from './preferences/preferences.service.js';
import { ProjectsService } from './projects/projects.service.js';
import { PromptBuilderService } from './prompt-builder/prompt-builder.service.js';
import { ReviewsService } from './reviews/reviews.service.js';
import { RulesService } from './rules/rules.service.js';
import { SearchService } from './search/search.service.js';
import { SettingsService } from './settings/settings.service.js';
import { SkillsService } from './skills/skills.service.js';
import { SystemService } from './system/system.service.js';
import { TasksService } from './tasks/tasks.service.js';
import { UsageService } from './usage/usage.service.js';
import { WorktreeService } from './worktree/worktree.service.js';

export const activityLogService = new ActivityLogService();
export const agentsService = new AgentsService();
export const authService = new AuthService();
export const skillsService = new SkillsService();
export const rulesService = new RulesService();
export const memoryService = new MemoryService();
export const tasksService = new TasksService();
export const projectsService = new ProjectsService();
export const settingsService = new SettingsService();
export const searchService = new SearchService();
export const agentProvidersService = new AgentProvidersService();
export const phasesService = new PhasesService();
export const reviewsService = new ReviewsService();
export const worktreeService = new WorktreeService();
export const promptBuilderService = new PromptBuilderService();
export const orchestratorService = new OrchestratorService();
export const briefGeneratorService = new BriefGeneratorService();
export const designContextGeneratorService = new DesignContextGeneratorService();
export const usageService = new UsageService();
export const chatService = new ChatService();
export const preferencesService = new PreferencesService();
export const systemService = new SystemService();
export const filesystemService = new FilesystemService();
export const packageExporterService = new PackageExporterService();
export const packageImporterService = new PackageImporterService();
export const marketplaceService = new MarketplaceService();
export const workflowRunnerService = new WorkflowRunnerService();
export const integrationsService = new IntegrationsService();
export const obsidianService = new ObsidianService();
export const supermemoryService = new SupermemoryService();
export const mcpServersService = new McpServersService();
export const heartbeatService = new HeartbeatService();
export const projectDocsService = new ProjectDocsService();
export const docsGeneratorService = new DocsGeneratorService();

export type { AgentContext, AgentDetail } from './agents/agents.types.js';
export type { DiffResult } from './orchestrator/index.js';
export type { ProjectContext, ProjectSummary } from './projects/projects.types.js';
export type { RuleDetail } from './rules/rules.types.js';
export type { SearchResult } from './search/search.types.js';
export type { SkillDetail } from './skills/skills.types.js';
export type { ObsidianSyncResult } from './integrations/obsidian.service.js';
export type { SystemInfo, UpdateCheckResult } from './system/system.service.js';
export type { DiffFile } from './worktree/worktree.service.js';
