import { AgentsService } from './agents/agents.service.js';
import { SkillsService } from './skills/skills.service.js';
import { RulesService } from './rules/rules.service.js';
import { MemoryService } from './memory/memory.service.js';
import { TasksService } from './tasks/tasks.service.js';
import { ProjectsService } from './projects/projects.service.js';
import { SettingsService } from './settings/settings.service.js';
import { SearchService } from './search/search.service.js';
import { ActivityLogService } from './activity-log/activity-log.service.js';
import { AgentProvidersService } from './agent-providers/agent-providers.service.js';
import { PhasesService } from './phases/phases.service.js';
import { ReviewsService } from './reviews/reviews.service.js';
import { WorktreeService } from './worktree/worktree.service.js';
import { PromptBuilderService } from './prompt-builder/prompt-builder.service.js';
import { OrchestratorService } from './orchestrator/orchestrator.service.js';
import { BriefGeneratorService } from './brief-generator/brief-generator.service.js';
import { ChatService } from './chat/chat.service.js';
import { PreferencesService } from './preferences/preferences.service.js';
import { SystemService } from './system/system.service.js';
import { FilesystemService } from './filesystem/filesystem.service.js';
import { PackageService } from './package/package.service.js';
import { IntegrationsService } from './integrations/integrations.service.js';
import { SupermemoryService } from './integrations/supermemory.service.js';

export const activityLogService = new ActivityLogService();
export const agentsService = new AgentsService();
export const skillsService = new SkillsService();
export const rulesService = new RulesService();
export const memoryService = new MemoryService();
export const tasksService = new TasksService();
export const projectsService = new ProjectsService();
export const settingsService = new SettingsService();
export const searchService = new SearchService();
export const agentProvidersService = new AgentProvidersService();
export const phasesService = new PhasesService();
export const reviewsService = new ReviewsService();
export const worktreeService = new WorktreeService();
export const promptBuilderService = new PromptBuilderService();
export const orchestratorService = new OrchestratorService();
export const briefGeneratorService = new BriefGeneratorService();
export const chatService = new ChatService();
export const preferencesService = new PreferencesService();
export const systemService = new SystemService();
export const filesystemService = new FilesystemService();
export const packageService = new PackageService();
export const integrationsService = new IntegrationsService();
export const supermemoryService = new SupermemoryService();

export type { AgentContext, AgentDetail } from './agents/agents.types.js';
export type { SkillDetail } from './skills/skills.types.js';
export type { RuleDetail } from './rules/rules.types.js';
export type { ProjectSummary, ProjectContext } from './projects/projects.types.js';
export type { DiffResult } from './orchestrator/orchestrator.types.js';
export type { SearchResult } from './search/search.types.js';
export type { DiffFile } from './worktree/worktree.service.js';
export type { SystemInfo } from './system/system.service.js';
export type { ImportPreview, ImportSummary } from './package/package.types.js';
