// Executors
import type { ExecutorConfig } from './executor.types.js';

export const KNOWN_EXECUTORS: ExecutorConfig[] = [
  {
    id: 'claude-code',
    name: 'Claude Code',
    command: 'claude',
    args: ['--print', '--verbose', '--output-format', 'stream-json', '--dangerously-skip-permissions'],
    outputFormat: 'stream-json',
    promptDelivery: 'stdin',
    mcpConfigFormat: 'claude',
    versionFlag: '--version',
    authCheck: { args: ['--print', '--output-format', 'text'], stdin: 'say ok', timeoutMs: 15000 },
    authHint: 'Run: claude /login',
    setup: { install: 'npm install -g @anthropic-ai/claude-code', auth: 'claude /login' },
    description: 'Anthropic Claude Code CLI agent with full MCP support',
    docsUrl: 'https://docs.anthropic.com/en/docs/claude-code',
    modelFlag: '--model',
    defaultModel: 'sonnet',
    modelPresets: [
      { value: 'opus', label: 'Claude Opus 4.6' },
      { value: 'sonnet', label: 'Claude Sonnet 4.6' },
      { value: 'haiku', label: 'Claude Haiku 4.5' },
    ],
  },
  {
    id: 'aider',
    name: 'Aider',
    command: 'aider',
    args: ['--yes-always', '--no-git'],
    promptDelivery: 'flag',
    promptFlag: '--message',
    mcpConfigFormat: 'none',
    versionFlag: '--version',
    setup: { install: 'pip install aider-chat', auth: 'export OPENAI_API_KEY=sk-...' },
    description: 'AI pair programming in your terminal',
    docsUrl: 'https://aider.chat',
    modelFlag: '--model',
    modelPresets: [
      { value: 'anthropic/claude-sonnet-4-6', label: 'Claude Sonnet 4.6', provider: 'anthropic' },
      { value: 'anthropic/claude-opus-4-6', label: 'Claude Opus 4.6', provider: 'anthropic' },
      { value: 'gpt-4.1', label: 'GPT-4.1', provider: 'openai' },
      { value: 'o3', label: 'o3', provider: 'openai' },
      { value: 'gemini/gemini-2.5-pro', label: 'Gemini 2.5 Pro', provider: 'google' },
      { value: 'gemini/gemini-2.5-flash', label: 'Gemini 2.5 Flash', provider: 'google' },
      { value: 'ollama_chat/qwen2.5-coder', label: 'Qwen 2.5 Coder (Ollama)', provider: 'ollama' },
      { value: 'ollama_chat/deepseek-r1', label: 'DeepSeek R1 (Ollama)', provider: 'ollama' },
      { value: 'ollama_chat/deepseek-coder-v2', label: 'DeepSeek Coder V2 (Ollama)', provider: 'ollama' },
      { value: 'ollama_chat/gemma3', label: 'Gemma 3 (Ollama)', provider: 'ollama' },
      { value: 'ollama_chat/llama3.2', label: 'Llama 3.2 (Ollama)', provider: 'ollama' },
      { value: 'ollama_chat/phi4', label: 'Phi-4 (Ollama)', provider: 'ollama' },
      { value: 'ollama_chat/codellama', label: 'Code Llama (Ollama)', provider: 'ollama' },
    ],
    providerMapping: [
      { providerType: 'anthropic', envVars: { ANTHROPIC_API_KEY: 'apiKey' } },
      { providerType: 'openai', envVars: { OPENAI_API_KEY: 'apiKey' } },
      { providerType: 'google', envVars: { GEMINI_API_KEY: 'apiKey' } },
      { providerType: 'openai-compatible', envVars: { OPENAI_API_KEY: 'apiKey', OPENAI_API_BASE: 'baseUrl' } },
      { providerType: 'ollama', envVars: { OLLAMA_API_BASE: 'baseUrl' } },
    ],
  },
  {
    id: 'codex',
    name: 'OpenAI Codex CLI',
    command: 'codex',
    args: ['--quiet'],
    promptDelivery: 'positional',
    mcpConfigFormat: 'none',
    versionFlag: '--version',
    setup: { install: 'npm install -g @openai/codex', auth: 'export OPENAI_API_KEY=sk-...' },
    description: 'OpenAI Codex CLI for code generation',
    docsUrl: 'https://github.com/openai/codex',
    modelFlag: '--model',
    modelPresets: [
      { value: 'gpt-5.2-codex', label: 'GPT-5.2 Codex', provider: 'openai' },
      { value: 'gpt-5.1-codex-mini', label: 'GPT-5.1 Codex Mini', provider: 'openai' },
      { value: 'o3', label: 'o3', provider: 'openai' },
    ],
    providerMapping: [{ providerType: 'openai', envVars: { OPENAI_API_KEY: 'apiKey' } }],
  },
  {
    id: 'gemini-cli',
    name: 'Gemini CLI',
    command: 'gemini',
    // -p: non-interactive (headless) mode; --yolo: auto-approve all actions; --output-format stream-json: structured logs
    args: ['--yolo', '--output-format', 'stream-json'],
    promptDelivery: 'flag',
    promptFlag: '-p',
    mcpConfigFormat: 'gemini',
    outputFormat: 'stream-json',
    versionFlag: '--version',
    setup: { install: 'npm install -g @google/gemini-cli', auth: 'gemini' },
    description: 'Google Gemini CLI agent (uses ~/.gemini/settings.json for MCP config)',
    docsUrl: 'https://github.com/google-gemini/gemini-cli',
    modelFlag: '--model',
    defaultModel: 'gemini-2.5-flash',
    modelPresets: [
      { value: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', provider: 'google' },
      { value: 'gemini-2.5-flash-lite', label: 'Gemini 2.5 Flash Lite (fastest)', provider: 'google' },
      { value: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro', provider: 'google' },
    ],
    providerMapping: [{ providerType: 'google', envVars: { GEMINI_API_KEY: 'apiKey' } }],
  },
  {
    id: 'amp',
    name: 'Amp',
    command: 'amp',
    args: [],
    promptDelivery: 'positional',
    mcpConfigFormat: 'none',
    versionFlag: '--version',
    setup: { install: 'npm install -g @sourcegraph/amp' },
    description: 'Sourcegraph Amp coding agent',
    docsUrl: 'https://ampcode.com',
    modelFlag: '--model',
    modelPresets: [{ value: 'claude-sonnet-4-6', label: 'Claude Sonnet 4.6' }],
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    command: 'opencode',
    args: [],
    promptDelivery: 'positional',
    mcpConfigFormat: 'none',
    versionFlag: '--version',
    setup: { install: 'go install github.com/opencode-ai/opencode@latest' },
    description: 'Open source AI coding agent',
    docsUrl: 'https://github.com/opencode-ai/opencode',
    modelFlag: '--model',
    modelPresets: [
      { value: 'anthropic/claude-sonnet-4-6', label: 'Claude Sonnet 4.6', provider: 'anthropic' },
      { value: 'openai/gpt-4.1', label: 'GPT-4.1', provider: 'openai' },
      { value: 'google/gemini-2.5-pro', label: 'Gemini 2.5 Pro', provider: 'google' },
      { value: 'google/gemini-2.5-flash', label: 'Gemini 2.5 Flash', provider: 'google' },
    ],
    providerMapping: [
      { providerType: 'anthropic', envVars: { ANTHROPIC_API_KEY: 'apiKey' } },
      { providerType: 'openai', envVars: { OPENAI_API_KEY: 'apiKey' } },
      { providerType: 'google', envVars: { GEMINI_API_KEY: 'apiKey' } },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama (Local AI)',
    command: 'ollama',
    spawnCommand: 'aider',
    args: ['--yes-always', '--no-git'],
    promptDelivery: 'flag',
    promptFlag: '--message',
    mcpConfigFormat: 'none',
    versionFlag: '--version',
    authCheck: { args: ['list'], timeoutMs: 5000 },
    authHint: 'Make sure Ollama is running: ollama serve',
    setup: {
      install: 'curl -fsSL https://ollama.ai/install.sh | sh && pip install aider-chat',
      auth: 'ollama serve',
    },
    description: 'Run open-source AI models locally — no API key required',
    docsUrl: 'https://ollama.ai',
    env: { OLLAMA_API_BASE: 'http://localhost:11434' },
    modelFlag: '--model',
    defaultModel: 'ollama_chat/qwen2.5-coder',
    modelPresets: [
      { value: 'ollama_chat/qwen2.5-coder', label: 'Qwen 2.5 Coder' },
      { value: 'ollama_chat/qwen2.5-coder:32b', label: 'Qwen 2.5 Coder 32B' },
      { value: 'ollama_chat/deepseek-r1', label: 'DeepSeek R1' },
      { value: 'ollama_chat/deepseek-coder-v2', label: 'DeepSeek Coder V2' },
      { value: 'ollama_chat/gemma3', label: 'Gemma 3' },
      { value: 'ollama_chat/llama3.2', label: 'Llama 3.2' },
      { value: 'ollama_chat/phi4', label: 'Phi-4' },
      { value: 'ollama_chat/mistral', label: 'Mistral' },
      { value: 'ollama_chat/codellama', label: 'Code Llama' },
    ],
  },
  {
    id: 'goose',
    name: 'Goose',
    command: 'goose',
    args: ['run', '--no-session', '-q'],
    promptDelivery: 'flag',
    promptFlag: '-t',
    mcpConfigFormat: 'none',
    versionFlag: '--version',
    setup: {
      install: 'curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh | bash',
      auth: 'goose configure',
    },
    description: 'Open source AI agent by Block with multi-provider and local model support',
    docsUrl: 'https://github.com/block/goose',
    modelFlag: '--model',
    modelPresets: [
      { value: 'claude-sonnet-4-6', label: 'Claude Sonnet 4.6', provider: 'anthropic' },
      { value: 'claude-opus-4-6', label: 'Claude Opus 4.6', provider: 'anthropic' },
      { value: 'gpt-4.1', label: 'GPT-4.1', provider: 'openai' },
      { value: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro', provider: 'google' },
      { value: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', provider: 'google' },
      { value: 'qwen2.5-coder', label: 'Qwen 2.5 Coder (Ollama)', provider: 'ollama' },
      { value: 'deepseek-r1', label: 'DeepSeek R1 (Ollama)', provider: 'ollama' },
      { value: 'deepseek-coder-v2', label: 'DeepSeek Coder V2 (Ollama)', provider: 'ollama' },
      { value: 'gemma3', label: 'Gemma 3 (Ollama)', provider: 'ollama' },
      { value: 'llama3.2', label: 'Llama 3.2 (Ollama)', provider: 'ollama' },
      { value: 'phi4', label: 'Phi-4 (Ollama)', provider: 'ollama' },
    ],
    providerMapping: [
      { providerType: 'anthropic', envVars: { ANTHROPIC_API_KEY: 'apiKey' } },
      { providerType: 'openai', envVars: { OPENAI_API_KEY: 'apiKey' } },
      { providerType: 'google', envVars: { GEMINI_API_KEY: 'apiKey' } },
      { providerType: 'openai-compatible', envVars: { OPENAI_API_KEY: 'apiKey', OPENAI_API_BASE: 'baseUrl' } },
      { providerType: 'ollama', envVars: { OLLAMA_HOST: 'baseUrl' } },
    ],
  },
];
