// External
import fs from 'node:fs';
import path from 'node:path';

// Lib
import { logger } from '../../../lib/logger.js';

const FILE_PATH = 'services/orchestrator/spawn/spawn-gitignore.ts';

const GITIGNORE_ESSENTIALS = `node_modules/
**/node_modules/
dist/
**/dist/
build/
.next/
.nuxt/
.turbo/
.pnpm-store/
*.tsbuildinfo
.env
.env.local
`;

/**
 * If the worktree has no .gitignore, writes a minimal one so agents
 * don't accidentally commit node_modules and other generated files.
 * If one already exists, appends any missing essential patterns.
 */
export function ensureGitignore(worktreePath: string): void {
  const gitignorePath = path.join(worktreePath, '.gitignore');
  try {
    if (fs.existsSync(gitignorePath)) {
      const existing = fs.readFileSync(gitignorePath, 'utf-8');
      const missingLines: string[] = [];
      for (const line of GITIGNORE_ESSENTIALS.split('\n')) {
        if (line && !existing.includes(line.replace('/', ''))) {
          missingLines.push(line);
        }
      }
      if (missingLines.length > 0) {
        const suffix = existing.endsWith('\n') ? '' : '\n';
        fs.appendFileSync(gitignorePath, `${suffix}\n# Added by Atlas\n${missingLines.join('\n')}\n`);
        logger.info(
          `${FILE_PATH} :: ensureGitignore - appended ${missingLines.length} patterns to existing .gitignore`,
        );
      }
    } else {
      fs.writeFileSync(
        gitignorePath,
        `# Generated by Atlas — prevent agents from committing build artifacts\n${GITIGNORE_ESSENTIALS}`,
      );
      logger.info(`${FILE_PATH} :: ensureGitignore - created .gitignore in worktree`);
    }
  } catch (error: unknown) {
    logger.warn(`${FILE_PATH} :: ensureGitignore - failed (non-fatal)`, error);
  }
}
