// External
import fs from 'node:fs';
import path from 'node:path';

// Shared
import type { Workspace } from '@atlas/shared';
import { TASK_STATUS } from '@atlas/shared';

// Repositories
import { workspacesRepository } from '../../../db/repositories/index.js';

// Services
import { activityLogService, projectsService, tasksService } from '../../index.js';
import { WorktreeService } from '../../worktree/index.js';

// Orchestrator
import { resolveSpawnOptions, buildPrompt } from './spawn-options.js';
import { structuredStageService } from './structured-stage.service.js';
import { activeProcesses } from '../shared/active-processes.js';

// Executors
import { executorRegistry } from '../../../executors/index.js';
import { spawnAgent } from '../../../executors/spawn-agent.js';

// Lib
import { AppError } from '../../../lib/errors.js';
import { logger } from '../../../lib/logger.js';

const FILE_PATH = 'services/orchestrator/workspace-spawn.service.ts';

const GITIGNORE_ESSENTIALS = `node_modules/
dist/
build/
.next/
.nuxt/
.turbo/
.pnpm-store/
*.tsbuildinfo
.env
.env.local
`;

export class WorkspaceSpawnService {
  private worktreeService = new WorktreeService();

  /**
   * If the worktree has no .gitignore, writes a minimal one so agents
   * don't accidentally commit node_modules and other generated files.
   * If one already exists, appends any missing essential patterns.
   */
  private ensureGitignore(worktreePath: string): void {
    const gitignorePath = path.join(worktreePath, '.gitignore');
    try {
      if (fs.existsSync(gitignorePath)) {
        const existing = fs.readFileSync(gitignorePath, 'utf-8');
        const missingLines: string[] = [];
        for (const line of GITIGNORE_ESSENTIALS.split('\n')) {
          if (line && !existing.includes(line.replace('/', ''))) {
            missingLines.push(line);
          }
        }
        if (missingLines.length > 0) {
          const suffix = existing.endsWith('\n') ? '' : '\n';
          fs.appendFileSync(gitignorePath, `${suffix}\n# Added by Atlas\n${missingLines.join('\n')}\n`);
          logger.info(`${FILE_PATH} :: ensureGitignore - appended ${missingLines.length} patterns to existing .gitignore`);
        }
      } else {
        fs.writeFileSync(gitignorePath, `# Generated by Atlas — prevent agents from committing build artifacts\n${GITIGNORE_ESSENTIALS}`);
        logger.info(`${FILE_PATH} :: ensureGitignore - created .gitignore in worktree`);
      }
    } catch (error: unknown) {
      logger.warn(`${FILE_PATH} :: ensureGitignore - failed (non-fatal)`, error);
    }
  }

  /** Creates a worktree, spawns the agent process, and opens a workspace. */
  async startWork(
    taskId: string,
    agentRuntimeId: string,
    baseBranch?: string,
    model?: string,
    providerId?: string,
    workflowStage?: 'brainstorm' | 'plan' | 'execute' | null,
    parentWorkspaceId?: string,
  ): Promise<Workspace> {
    const FUNCTION_NAME = 'startWork';
    try {
      const task = await tasksService.getById(taskId);

      if (!task.projectId) {
        throw new AppError('Task must be assigned to a project with a local path', { status: 400 });
      }

      const project = await projectsService.getById(task.projectId);

      if (!project.localPath) {
        throw new AppError(`Project "${project.name}" has no local path configured`, { status: 400 });
      }

      if (!fs.existsSync(project.localPath)) {
        throw new AppError(`Project local path does not exist: ${project.localPath}`, { status: 400 });
      }

      const executor = executorRegistry.getById(agentRuntimeId);
      if (!executor) {
        throw new AppError(`Unknown agent runtime: ${agentRuntimeId}`, { status: 400 });
      }

      const existing = workspacesRepository.findByTaskId(taskId);
      if (existing && (existing.status === 'running' || existing.status === 'pending')) {
        throw new AppError('A workspace is already active for this task', { status: 409 });
      }

      const { resolvedModel, spawnOpts } = await resolveSpawnOptions(executor, task.agentId, model, providerId);

      // Determine the effective workflow stage for this run.
      const effectiveStage = workflowStage ?? (task.workflowEnabled ? (task.workflowStage ?? 'brainstorm') : null);
      const isStructuredStage = effectiveStage === 'brainstorm' || effectiveStage === 'plan';

      if (isStructuredStage) {
        const structuredResult = await structuredStageService.run(
          effectiveStage as 'brainstorm' | 'plan',
          task,
          project,
          taskId,
          agentRuntimeId,
          resolvedModel ?? null,
          providerId,
          parentWorkspaceId,
        );
        if (structuredResult) return structuredResult;
        // Provider unavailable — fall through to CLI execution
      }

      // Resolve which branch to base the worktree on:
      //   1. Explicit baseBranch from the request
      //   2. Project's configured default branch
      //   3. Auto-detect (main/master) — handled inside worktreeService.create
      const resolvedBaseBranch = baseBranch || project.defaultBranch || undefined;

      const { worktreePath, branchName } = this.worktreeService.create(
        project.localPath,
        taskId,
        task.name,
        resolvedBaseBranch,
      );

      // Ensure worktree has a .gitignore so agents don't commit generated files
      this.ensureGitignore(worktreePath);

      // Copy plan artifact into the worktree so the execute agent has it
      if (effectiveStage === 'execute') {
        const srcPlan = path.join(project.localPath, 'specs', 'atlas-plan.md');
        if (fs.existsSync(srcPlan)) {
          const destDir = path.join(worktreePath, 'specs');
          fs.mkdirSync(destDir, { recursive: true });
          fs.copyFileSync(srcPlan, path.join(destDir, 'atlas-plan.md'));
          logger.info(`${FILE_PATH} :: startWork - copied atlas-plan.md into worktree`);
        }
      }

      const workspace = workspacesRepository.insert({
        taskId,
        projectId: project.id,
        agentId: task.agentId ?? null,
        agentRuntime: agentRuntimeId,
        model: resolvedModel ?? null,
        branchName,
        worktreePath,
        status: 'pending',
        workflowStage: effectiveStage ?? null,
        parentWorkspaceId: parentWorkspaceId ?? null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });

      const prompt = await buildPrompt({
        taskId,
        projectId: project.id,
        agentId: task.agentId,
        hasMcpAccess: executor.mcpConfigFormat !== 'none',
        workflowStage: effectiveStage,
      });

      const cwd = executor.usesProjectRoot ? project.localPath : worktreePath;
      const result = await spawnAgent(
        workspace.id,
        executor,
        cwd,
        prompt,
        {
          onCompleted: (output) => {
            activeProcesses.delete(workspace.id);

            // Safety net: commit any changes the agent left uncommitted
            this.worktreeService.ensureChangesCommitted(worktreePath);

            const ws = workspacesRepository.update(workspace.id, {
              status: 'completed',
              output,
              completedAt: new Date().toISOString(),
            });

            const isWorkflowStage = ws.workflowStage === 'brainstorm' || ws.workflowStage === 'plan';
            const nextStatus = isWorkflowStage ? TASK_STATUS.AWAITING_APPROVAL : TASK_STATUS.IN_REVIEW;
            tasksService.update(ws.taskId, { status: nextStatus }).catch((e) => {
              logger.warn(`${FILE_PATH} :: spawnAgent - failed to update task status after completion`, e);
            });
            activityLogService.log({
              projectId: ws.projectId,
              taskId: ws.taskId,
              workspaceId: workspace.id,
              agentId: ws.agentId,
              eventType: 'agent_completed',
              description: 'Agent completed successfully',
              metadata: {},
            });
            logger.info(`${FILE_PATH} :: spawnAgent - process completed for workspace ${workspace.id}`);
          },
          onFailed: (output, error) => {
            activeProcesses.delete(workspace.id);
            const ws = workspacesRepository.update(workspace.id, {
              status: 'failed',
              output,
              completedAt: new Date().toISOString(),
            });
            tasksService.update(ws.taskId, { status: TASK_STATUS.TODO }).catch((e) => {
              logger.warn(`${FILE_PATH} :: spawnAgent - failed to reset task status`, e);
            });
            activityLogService.log({
              projectId: ws.projectId,
              taskId: ws.taskId,
              workspaceId: workspace.id,
              agentId: ws.agentId,
              eventType: 'agent_failed',
              description: `Agent failed: ${error ?? 'unknown error'}`,
              metadata: { error },
            });
            logger.error(`${FILE_PATH} :: spawnAgent - process failed for workspace ${workspace.id}: ${error}`);
          },
        },
        spawnOpts,
      );

      activeProcesses.set(workspace.id, result.process);
      workspacesRepository.update(workspace.id, {
        status: 'running',
        pid: result.process.pid ?? null,
        startedAt: new Date().toISOString(),
      });

      await tasksService.update(taskId, { status: TASK_STATUS.IN_PROGRESS });

      activityLogService.log({
        projectId: project.id,
        taskId,
        workspaceId: workspace.id,
        agentId: task.agentId,
        eventType: 'agent_started',
        description: `Agent started on task: ${task.name}`,
        metadata: { agentRuntime: agentRuntimeId, branchName, model: resolvedModel },
      });

      return workspacesRepository.findByIdOrThrow(workspace.id);
    } catch (error: unknown) {
      logger.error(`${FILE_PATH} :: ${FUNCTION_NAME}`, error);
      if (error instanceof AppError) throw error;
      throw new AppError('Failed to start work', { cause: error });
    }
  }
}

export const workspaceSpawnService = new WorkspaceSpawnService();
